<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="BajaPaciente.aspx.cs" Inherits="Vistas.BajaPaciente" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Baja Paciente</title>
    <link href="../../Estilos/Estilos.css" rel="stylesheet" type="text/css" />
         <style>
         </style>
</head>
<body>
    <form id="form1" runat="server">
          <header>
              <p>Clinica Pacheco</p>
              <nav>
                  <ul class="nav-bar">
                     <li>
                         <a>
                            <asp:HyperLink ID="hlInicio" runat="server" NavigateUrl="~/Inicio/InicioAdministrador.aspx">Inicio</asp:HyperLink>
                         </a>
                     </li>
                      <li>
                          <asp:Label ID="lblUsuario" runat="server" Text="Usuario:"></asp:Label>
                          <asp:Label ID="lblUsuarioEnSesion" runat="server" CssClass="auto-style1"></asp:Label>
                      </li>
                      <li>
                          <asp:Button ID="btnCerrarSesion" runat="server" Text="Cerrar Sesion" CssClass="btn-cerrar-sesion" />
                      </li>
                  </ul>
              </nav>
          </header>
        <div class="wrapper">
            <h1><asp:Label ID="lblTitulo" runat="server" Font-Size="XX-Large" Text="Baja Paciente"></asp:Label></h1>
           
            <br />
            <table class="auto-style1">
                <tr>
                    <td class="auto-style3">
                        <asp:Label ID="lblBuscarPorDNI" runat="server" Text="DNI paciente:"></asp:Label>
                    </td>
                    <td class="auto-style7">
                        <asp:TextBox ID="txtBuscarPorDNI" runat="server" CssClass="auto-style5" placeholder="DNI"></asp:TextBox>
                    </td>
                    <td>
                        <asp:RequiredFieldValidator ID="rfvDniPaciente" runat="server" ControlToValidate="txtBuscarPorDNI" Display="None">*Completar campo</asp:RequiredFieldValidator>
                    </td>
                </tr>
                </table>

                        <br />

                        <asp:Button ID="btnGuardar" runat="server" Text="Buscar" CssClass="btn" />

             <table>
               
                <tr>
                    <td class="auto-style3" colspan="3">
                        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True">
                            <Columns>
                                <asp:BoundField HeaderText="DNI" />
                                <asp:BoundField HeaderText="Nombre" />
                                <asp:BoundField HeaderText="Apellido" />
                            </Columns>
                        </asp:GridView>
                    </td>
                </tr>
               
            </table>
        </div>
    </form>
</body>
</html>
